### ISSUE TITLE
under multi gopath, revel new always under the first path

### ISSUE THREAD

**Issue by ziyouchutuwenwu** [revel/revel#1004]
here is my gopath
```
export GOROOT=~/golang/go
export GOPATH=~/golang/3rdLibs:~/golang/myLibs:~/golang/myApps
export GOBIN=
export PATH=$PATH:$GOROOT/bin:${GOPATH//://bin:}/bin
```

when i execute " revel new hello", it creates the project always under ~/golang/3rdLibs, that's where i wish to place 3rd libs, i don't like "revel" to create under this path.
i have to move to ~/golang/myApps manully each time, it seems much bad.

another framework beego, it has the simular command, "bee new xxx".( maybe copied from revel )
it created project from relative path, it's much better for me.
could you please provide an option to create a project in relative path or an absolute path which can be defined by user?

thanks very much!

**Comment by alkchr** [comment]
:+1: A legit request. Not difficult to implement.

**Comment by pedromorgan** [comment]
Is this a revel/cmd issue ??

**Comment by alkchr** [comment]
@pedromorgan Yes, it is.

**Comment by jeevatkm** [comment]
@alkchr can you please share your thoughts on this request?

**Comment by alkchr** [comment]
@jeevatkm Now Revel uses [the first](https://github.com/revel/cmd/blob/master/revel/new.go#L100) `GOPATH` in the list no matter what. Relative paths are not supported.
When user is running `revel run ./something` it creates `DEFAULT_GOPATH/src/something` ignoring the `./` part. Meanwhile we could do the following:
1. User runs `revel run ./something`.
2. We transform `./something` to the absolute form (e.g. `/home/johndoe/Go/src/github.com/johndoe/something`).
3. We check whether the absolute form from the step (2) is inside one of the GOPATHs.
  * If it is, project is created.
  * Otherwise, we notify user that project must be inside GOPATH.

**Comment by jeevatkm** [comment]
@alkchr doing anywhere path or relative path is not that easy to do with current follow. As you described in step 2, if we transform and make a choice it might lead to further questions.

How about this? If revel finds more than one `GOPATH` then give a choice to user to choose.

For example:
```bash
.... Revel found multiple GOPATH, please choose one from it?
1. ~/golang/3rdLibs
2. ~/golang/myLibs
3. ~/golang/myApps

Enter your choice (default is 1): 3

... generate a project ...
```

**Comment by alkchr** [comment]
> doing anywhere path or relative path is not that easy to do with current follow. 

@jeevatkm Could you please rephrase, I'm not sure I understand.

> As you described in step 2, if we transform and make a choice it might lead to further questions.

No further questions required. We are using `filepath.Abs` to make absolute path out of relative one (the input path is relative to the directory where you run `revel run` not to the `GOPATH`).
And to make sure the absolute path is within some of the `GOPATH`s, you check whether it `HasPrefix` `GOPATH[0]`, `GOPATH[1]` or `GOPATH[N]`. It's that easy.

**Comment by jeevatkm** [comment]
@alkchr I have described the above comment inline with user mentioned problem, not for relative path support.

> when i execute " revel new hello", it creates the project always under ~/golang/3rdLibs, that's where i wish to place 3rd libs, i don't like "revel" to create under this path.
> i have to move to ~/golang/myApps manully each time, it seems much bad.

Did I explained it clearly?

**Comment by alkchr** [comment]
It's exactly about relative paths:
> another framework beego, it has the simular command, "bee new xxx".
> **it created project from relative path**, it's much better for me.

Here is a related function of Beego: https://github.com/beego/bee/blob/master/new.go#L57
It does exactly what I've described. Except it doesn't support absolute paths at all: input is always considered as relative that's why `./` at the beginning is not required.

**Comment by jeevatkm** [comment]
@alkchr I had look on given reference and I understand your point, thanks.  My bad I was thinking of `./` or `../` inputs.

I'm marking this for v0.13, I will take care.

**Comment by jeevatkm** [comment]
done!
