### ISSUE TITLE
Return default file with Static routing

### ISSUE THREAD

**Issue by archeious** [revel/revel#1029]
Is it currently possible to return a default file if the route matches the static routing rule but the file does not exist.  e.g.,  

GET     /img/thumbnail/*filepath                            Static.Serve("public/img/thumbnail")

I want to return a default thumbnail if a thumbnail does not exist.

**Comment by alkchr** [comment]
@archeious I think you'll have to clone `static` module and update [related](https://github.com/revel/modules/blob/master/static/app/controllers/static.go#L113-L116) fragment. Or, alternatively embed `static` controller and create you own wrapper action:

```go
package controllers

import (
	s "github.com/revel/modules/static/app/controllers"
	"github.com/revel/revel"

)

type App struct {
	*revel.Controller
	s.Static
}

func (c App) ServeThumbnail(prefix, defaultTh, filepath string) revel.Result {
	// Show the requested file if it does exist.
	res := c.Serve(prefix, filepath)
	switch res.(type) {
	case *revel.BinaryResult:
		return res
	}

	// Otherwise, show the default thumbnail instead.
	return c.Serve(prefix, defaultTh)
}
```
Then use it in your routes as follows:
```
GET     /thumbnail/*filepath                App.ServeThumbnail("public", "img/favicon.png")
```
Open [http://localhost:9000/thumbnail/xxx](http://localhost:9000/thumbnail/xxx). Then [http://localhost:9000/thumbnail/img/glyphicons-halflings.png](http://localhost:9000/thumbnail/img/glyphicons-halflings.png) (I assume, this is a newly generated app; otherwise test with some other file names).

**Comment by archeious** [comment]
Thank you, that is exactly what I was needing.
