### ISSUE TITLE
compressableMimes linear search in compress.go

### ISSUE THREAD

**Issue by ganpati** [revel/revel#1036]
In compress.go, I see a list of mime types supported.
The code does a linear search over this list - I request a map[string]bool instead.

			for _, compressableMime := range compressableMimes {
				if responseMime == compressableMime {
					shouldEncode = true

var compressableMimes = [...]string{
	"text/plain",
	"text/html",
	"text/xml",
	"text/css",
	"application/json",
	"application/xml",
	"application/xhtml+xml",
	"application/rss+xml",
	"application/javascript",
	"application/x-javascript",
}

**Comment by alkchr** [comment]
Iteration over a small number of elements is faster than getting an element from a `map`.
That's the case when we need up to 9 iterations.

Though, extra allocations kill the benefit:
```go
for _, compressableMime := range compressableMimes {
}
```
To use the advantage of a list of elements it should be:
```go
for i := range compressableMimes {
	if responseMime == compressableMimes[i] {
	}
}
```

**Comment by pedromorgan** [comment]
a golang issues, not revel

**Comment by alkchr** [comment]
@pedromorgan Why not? Looks like exactly Revel's issue to me. Not critical, but still.

**Comment by brendensoares** [comment]
@alkchr how is iterating with an index better than with a range value?

**Comment by alkchr** [comment]
@brendensoares In the following case we are getting a copy on every iteration:
```go
for _, compressableMime := range compressableMimes {
}
```
In this one we aren't:
```go
for i := 0; i < len(compressableMimes); i++ {
}
```
Though, I've just benchmarked it and it looks like that's not necessarily the case for the small array of strings (not complex types). What I get looks more like a measurement error.

But the map vs. loop for small number of elements is still the case. The complexity of the former is O(1+c), and of the latter is O(n). If n is small enough, O(n) < O(1+c).
That's why non standard MUX implementations use [their](https://github.com/julienschmidt/httprouter/blob/master/router.go#L97) [own](https://github.com/naoina/denco/blob/master/router.go#L100) slice based data structures instead of maps for parameters.

**Comment by brendensoares** [comment]
Thanks for the info @alkchr I assume range returned a reference to the value, not a duplicate value.

**Comment by jeevatkm** [comment]
* First of all this is not a issue with Revel. It's a enhancement to Revel in-terms of performance
* Using range or index based access is not gonna make difference

I believe, we can go with `map[string]bool` usage like @ganpati mentioned in the issue. Then code will look like in `prepareHeaders`-
```go
if _, found := compressableMimes[responseMime]; found {
	shouldEncode = true
	c.Header().Set("Content-Encoding", c.compressionType)
	c.Header().Del("Content-Length")
}
```
