### ISSUE TITLE
filter for pages only

### ISSUE THREAD

**Issue by u007** [revel/revel#1046]
Hi,

I think there is a need for regex filter for url before a filter is executed...
it seems to apply header for static files as well such as images and css and js

**Comment by pedromorgan** [comment]
Is this for static, or dynamic ??

**Comment by u007** [comment]
I think it will be nice that we can set filter for both, but I'm actually
talking about filter for csrf that will only applies to HTML format or non
static paths

**Comment by alkchr** [comment]
> it seems to apply header for static files as well such as images and css and js

That's due to the fact that in Revel static assets are served using [`Serve` action](https://github.com/revel/modules/blob/master/static/app/controllers/static.go#L45-L53). So, there is no difference between static files and dynamic actions, actions take part in both cases.
When implementing CSRF protection you can check whether current `c.Controller.Action` to make sure it is not equal to `Static.Serve`. Though, this feels kind of hacky.

**Comment by u007** [comment]
Yes I added my work around aka the manual if before running filter. Would
be nice if we have option to pass in file extension. But this will need the
.ext in route to work as well

**Comment by notzippy** [comment]
You can use `FilterConfigurator` to change the chain of filters for an action. For example
` FilterAction(Serve.Static).Remove(SessionFilter)`
