### ISSUE TITLE
Possible fsnotify race condition

### ISSUE THREAD

**Issue by ptman** [revel/revel#1117]
Build using -race and run. On startup I get:

    ==================
    WARNING: DATA RACE
    Read at 0x00c420628280 by goroutine 58:
      gopkg.in/fsnotify%2ev1.(*Watcher).readEvents()
          src/gopkg.in/fsnotify.v1/inotify.go:182 +0x148
    
    Previous write at 0x00c420628280 by main goroutine:
      github.com/revel/revel.(*Watcher).Listen()
          src/github.com/revel/revel/watcher.go:56 +0xc0
      github.com/revel/revel.InitServer()
          src/github.com/revel/revel/server.go:101 +0x2ca
      github.com/revel/revel.Run()
          src/github.com/revel/revel/server.go:137 +0x34b
      main.main()
          src/foo/app/tmp/main.go:865 +0x13cba
    
    Goroutine 58 (running) created at:
      gopkg.in/fsnotify%2ev1.NewWatcher()
          src/gopkg.in/fsnotify.v1/inotify.go:61 +0x4e9
      github.com/revel/revel.(*Watcher).Listen()
          src/github.com/revel/revel/watcher.go:47 +0x6d
      github.com/revel/revel.InitServer()
          src/github.com/revel/revel/server.go:101 +0x2ca
      github.com/revel/revel.Run()
          src/github.com/revel/revel/server.go:137 +0x34b
      main.main()
          src/foo/app/tmp/main.go:865 +0x13cba
    ==================

**Comment by notzippy** [comment]
The issue here is that in revel we modified the watcher.Events channel and watcher.Errors channel to add the ability to watch more then one [file change](https://github.com/revel/revel/blob/master/watcher.go#L56) this causes a race condition to be reported because previously these objects were closed by a defer close(w.Errors) in inotify.go.  This is not an issue when running in `prod` mode since the files are not watched.
