### ISSUE TITLE
why secretKey in revel.go is private?

### ISSUE THREAD

**Issue by runner-mei** [revel/revel#1127]
I need edit secretKey in OnAppStart, as follows:

revel.OnAppStart(func(){
   revel.SecretKey = // read from database
})

why I need edit secretKey?
I  has mutiple app, some app is develop with java, some app is develop with revel.
I share session in all app, So secretKey must is same in all app.

**Comment by notzippy** [comment]
You can manually set the secret key in revel in the app.conf. The other frameworks must be able to do this as well, so I am not sure why you need to store the key in the database ?

**Comment by runner-mei** [comment]
some app is develop with java playframework.

secret key is distribution in different configuration files, So I think  store them together in one place

**Comment by notzippy** [comment]
Do the other frameworks allow you to change the key on the fly ? (it looks like in playframework this is a read only value as [well](https://www.playframework.com/documentation/2.5.x/ApplicationSecret)). To me it makes more sense to set the key values in your configuration file. If you want to use different values for production and development that is possible by moving the key to the appropriate section. 

The other thing you can do is implement your own SessionFilter class that saves and secures the cookie with the key from the database. Then use your SessionFilter instead of revels built in one

I can bring this topic up at the next general meeting this week and see what is said but the above options should work as well

**Comment by runner-mei** [comment]
playframework can custom load config file.
I  do it by implement custom SessionFilter.

**Comment by runner-mei** [comment]
Can load config file by custom hook.

**Comment by notzippy** [comment]
I agree, there is not much gained by the secret key being private. Do you want to expose it by adding a Setter method with a PR  ?

**Comment by runner-mei** [comment]
nice

**Comment by notzippy** [comment]
should be in new release tonight
