### ISSUE TITLE
Template rendering difference on windows

### ISSUE THREAD

**Issue by notzippy** [revel/revel#1128]
Given the following template
```
<script>
    <% if(event.Type == 'join') { %>
    <% } %>
</script>
```
on ubuntu it works fine

But Windows renders it like
```
<script>
    &lt;% if(event.Type == 'join') { %>
    &lt;% } %>
</script>
```
Go version 1.8, this [code](https://play.golang.org/p/OR8yszGEBJ) seems to work fine on ubuntu and windows. So there may be some issues when template is being built inside of revel (perhaps)

A good example is the chat application

**Comment by noway** [comment]
Reporing the same issue in #1137  (oh ah, seems like a duplicate)

Happens for me under Arch Linux. Might be a regression under latest version of the templating engine?

**Comment by noway** [comment]
Any work around for that?

**Comment by notzippy** [comment]
@noway Use linux :-P .. 

But seriously we are looking into this and if possible it will be fixed either this weekend or the next.

**Comment by brendensoares** [comment]
So steps to reproduce:
1. `revel new bug`
2. Add go template braces inside of a `<script>` tag within the `app/views/App/Index.html` view content
3. Load `localhost:9000` in browser and see incorrectly rendered content

Right?

**Comment by shawncatz** [comment]
@notzippy this will be fixed as part of your template engine work correct? That's currently slated for v0.15, so I'm going to move this to v0.15 as well

**Comment by noway** [comment]
@notzippy please read the topic carefully, I'm under Arch Linux and experiencing this problem.

[type-bug-windows] is incorrect. At least Linux and windows are affected.

@brendensoares 
Steps to reproduce:

1. `revel new bug`
2. Copypaste this in views/App/Index.html:
```
<script type="text/template">
    <% if(event.Type == 'join') { %>
    <% } %>
</script>
```
3. See `view-source:http://localhost:9000/`

Clarification. The issue happens (at least for me?) when the `type` attribute is not `text/javascript`. Seems to be rendering fine when `type="text/javascript"` is present. Also renders ok when no `type` attribute is present at all. Not preferable workaround though because browser would try to execute the content in those cases.

I venture a guess that it has something to do with special treatment of javascript script tags and potential workaround lays in using CDATA?

**Comment by noway** [comment]
Even CDATA renders incorrectly in cases where javascript is not implied.

```
<script type="text/template">
<![CDATA[
    <% if(event.Type == 'join') { %>
    <% } %>
]]>
</script>
```
becomes

```

<script type="text/template">
&lt;![CDATA[
    &lt;% if(event.Type == 'join') { %>
    &lt;% } %>
]]>
</script>
```

**Comment by notzippy** [comment]
@noway Quite right, I am looking into this issue

**Comment by notzippy** [comment]
This issue is because html/template is attempting to safely format the code, which is breaking this aspect of it. You can provide a custom tag to protect the content [like this](https://groups.google.com/forum/#!msg/golang-nuts/8y6by6SERyU/XQRnbw3aBhwJ) example https://play.golang.org/p/7l7UywD20B

The only suggestion I can make is to protect the code using the raw command
