### ISSUE TITLE
Please support template inheritance  

### ISSUE THREAD

**Issue by hfeeki** [revel/revel#123]
I found golang's default template system do not support template inheritance like django/jinja2 , but i after some search, I found a solution to support inheritance: 
http://stackoverflow.com/questions/11467731/is-it-possible-to-have-nested-templates-in-go-using-the-standard-library-googl
But the problem is : we maybe need to add a "base-template" field to config, and default set all of other templates inherit from the base template. 
Any tips on where I should look to make changes? Thanks.

**Comment by pedromorgan** [comment]
Template Dream is still open and tagged

**Comment by robfig** [comment]
@pedromorgan should give github.com/robfig/soy a shot :)

**Comment by notzippy** [comment]
@robfig :+1:

**Comment by anonx** [comment]
Hi, @flosch. Is there any reason why pongo2's `template.Execute` method expects `pongo2.Context` rather than `interface{}`? We have already had our own `Context` in revel.
And there are plans to make template engine configurable.

Meanwhile, other template engines receive `data interface{}` rather than variable of their own type:

[**template**](https://golang.org/pkg/html/template/#Template.Execute):
```go
func (t *Template) Execute(wr io.Writer, data interface{}) error
```
[**github.com/hoisie/mustache**](https://github.com/hoisie/mustache):
```go
func Render(data string, context ...interface{}) string
```

or return standard `template.Template` that has `Execute(wr io.Writer, data interface{})`:

[**github.com/eknkc/amber**](https://github.com/eknkc/amber)
```go
func Compile(input string, options Options) (*template.Template, error)
```

[**github.com/yosssi/ace**](https://github.com/yosssi/ace)
```go
func Load(basePath, innerPath string, opts *Options) (*template.Template, error)
```

**Comment by flosch** [comment]
@anonx `pongo2.Context` is a simple `map[string]interface{}` since pongo2 provides all objects by their name in the template. For example, passing a pongo2.Context`{"person": personObject, "makeSomethingUseful": func(...) {}}` makes these two symbols (obj and func) available and they can be used, e. g. by printing out `{{ person.Name }}` or using the function in `{% if makeSomethingUseful(person.Foo) %}...{% endif %}`. Currently, I have no plans to drop this support, but you're free to pass any `map[string]interface{}` as a context (and typecasting it to `pongo2.Context`). If you making sure that your `interface{}` is a of type `map[string]interface{}`, then you can pass it easily to pongo2. If it's not a map, you could create a correct context like this: `pongo2.Context{"obj": givenInterface}`.

**Comment by notzippy** [comment]
Adding https://github.com/revel/revel/pull/1003 , closing this
