### ISSUE TITLE
Error when using golang/deps 

### ISSUE THREAD

**Issue by MichaelRBond** [revel/revel#1231]
Attempting to start a new project using GoLang/Deps ( https://github.com/golang/dep ) as the package manager. 

Error encountered: `panic: reflect: call of reflect.Value.Type on zero Value`

Steps to reproduce above error:

1. `revel new test1`
1. `cd test1`
1. `dep init`
1. `revel run test1`
1. navigate to `localhost:9000` in web browser. Causes error

However, if you run the new app before doing a `dep init` the app runs. Steps to reproduce working app:

1. `revel new test1`
1. `revel run test1`
1. ctrl+c
1. `cd test1`
1. `dep init`
1. `revel run test1`
1. navigate to `localhost:9000` in web browser. Does not cause error.

Also, if i delete app/tmp/main.go and run it again it still works.

Versions:
1. Go: `go version go1.9 linux/amd64`
1. Revel: 
```
~
~ revel! http://revel.github.io
~
Version(s):
   Revel v0.17.1 (2017-07-14)
   go1.9 linux/amd64
```
1. Dep: 0.3.0

**Comment by notzippy** [comment]
Revel automatically downloads dependent packages and places them in the go
path. Check to make sure there are no revel packages (outside of your go
dep filler) that exist

**Comment by notzippy** [comment]
The cause of this is because revel downloads missing packages automatically using a `go get <packagename>` command. This places the packages outside of the vendor folder causing the for mentioned issues. A possible solution is to change the revel code so that if a vendor folder is found it runs the deps command to add the new package
