### ISSUE TITLE
How to pass references

### ISSUE THREAD

**Issue by vikram-rawat** [revel/revel#1240]
I would agree with a closed issue. for a newcomer your document is totally technical. I am tying to figure out how to add a custom css on the top of a normal app. and I am not able to get this simple answer.

=========header.html
 ```
 {{range .styles}}
      <link rel="stylesheet" type="text/css" href="/public/{{.}}">
   {{end}}
```
==========index.html
`{{set . "styles" ""css/style.css""}}`
===========

and it just doesn't work

same goes for href

when I set `href=www.google.com`

it tells me

=====Not Found
No matching route found: /www.google.com
===========

and your documentation doesn't describe how to do it. which path has to start from which folder. Like there are default paths.

Please update your documents. It should be made for novice like me because pros can get away just by reading the code, I can't.

Can you tell me how to solve this problem of adding custom css and href... Please I am trying to learn go and revel at the same time. Don't make it more daunting as it already is.

**Comment by notzippy** [comment]
Sorry you are finding the documentation a little technical side - sometimes when you work with it so long it is hard to see it from a new perspective. The command you are looking for is `{{append . "styles" "vendors/bootstrap/dist/css/bootstrap.min.css"}}` [see here](http://revel.github.io/manual/templates-go.html#append)

If you have suggestions on how to improve the manual we are open for suggestions. The [tutrorial section](http://revel.github.io/tutorial/requestflow.html) in the manual makes use of the `append` function as well. Go has a unique [template syntax](https://golang.org/pkg/text/template/), the html template extends from the text template so that is where you can find a lot of the core functionality.

p.s. I did respond to you on gitter as well

**Comment by vikram-rawat** [comment]
Thanks for replying so quickly. It's just I have started to code recently and Chose golang to be my serverside programming and found revel being the easiest one so far. But I just don't like the documentation as it's written by someone who was trying to tell the basics quickly and let you learn through manual.

Instead we needed someone who could write down everything slowly at least till you can connect the basic structure. After that manual would have been good. I mean it's hard to figure out which function or line is responsible for which action.

NO offense I like your framework very much. But it's documentation not that much. it's clearly not for new coders or beginners.

But thanks for this framework anyways. Hope I am going to ping you a lot on gitter from now. :-)

**Comment by vikram-rawat** [comment]
Just for guidance regarding documentation. Everything that I have learned is from building RShiny. Just take some time and check these links.

http://shiny.rstudio.com/tutorial/

or 

https://rstudio.github.io/shinydashboard/

A person who knows nothing about anything can get started within a week without having to stumble on any pitfall.

===========
footnote:- I am not comparing you to Rstudio they are different than you guys. You Rock too...

Its just I believe the documentation should always be like this. Alwasy consider the person knows nothing. Because if he does he will skip it anyways.

Not trying to be judgemental it's just a suggestion hope you wont take it the wrong way.
