### ISSUE TITLE
Response 204 : Http: request method or response status code does not allow body

### ISSUE THREAD

**Issue by gourlaa** [revel/revel#1321]
Hi!

Thanks for your framework!

We have an issue with empty response (204), do you any render for 204 answer?

Currently we are doing : 
b.Response.Status = 204
return b.RenderJSON(nil)

However we are getting this message : ERROR 16:45:50  revel results.go:320: Apply: Response write failed:             section=results error="http: request method or response status code does not allow body"

On some other framework you can do an abort or send nil, but I didn't see anything on the revel documentation?

Thanks,
Pierre

**Comment by notzippy** [comment]
204 header means you cannot send a content body, but the JSON form of nil is the word `null`. And the server engine then complains about this. If you where to return a `b.RenderText("")` it would all be fine. I am not sure if this should be checked on Revel's side, since this is a programming error.

If sending a 204 response for an empty JSON object would be your normal response you could consider implementing your own result to do this like:
```
type Result204 struct {

}
func (Result204) Apply (req *revel.Request, resp *revel.Response) {
	resp.WriteHeader(204,"")
}
var result204 = Result204{}

....
// Then in the controller code you can return
return result204
```
or you can extend the RenderJSONResult to check to see if the object is nil and automatically return a 204 if it is... 

If you need more help with this add to this report, otherwise I am closing this.
