### ISSUE TITLE
RenderBinary forces content-type

### ISSUE THREAD

**Issue by rami-dabain** [revel/revel#1345]
RenderBinary(...) forces the response to have content-type:octet-stream which is a problem if you want to pass a css / image file as those will not be accepted by the browsers (file data stored in memory , not using the Static module)

suggestion would be not to overwrite the content-type header if it was set before

**Comment by notzippy** [comment]
The issue is that the content type is set when the request is initialized [here](https://github.com/revel/revel/blob/master/http.go#L86). So Revel does not know if the content type is changed. If you set the `c.ContentType=""` before you call the `c.RenderBinary` function, this will cause the [apply function](https://github.com/revel/revel/blob/master/results.go#L396) to set the content header according to the file extension. Which is (I think) what you want.
