### ISSUE TITLE
Using a standard HTTP middleware function

### ISSUE THREAD

**Issue by Julio-Guerra** [revel/revel#1504]
Hello,

I had a quick look at Revel but I couldn't find a way to use a `http.Handler` function with Revel.
Is there an official way to integrate a `net/http` middleware function of type `func (http.Handler) http.Handler`?

**Comment by notzippy** [comment]
It's there, see https://revel.github.io/manual/custom-mux.html

**Comment by Julio-Guerra** [comment]
@notzippy this page doesn't show at all how to **wrap** a Revel router with a standard net/http middleware.

**Comment by notzippy** [comment]
@Julio-Guerra it appears you have a predefined server and you want to basically invoke the controllers from your server. That is implemented using the [Server Engine](https://revel.github.io/manual/server-engine.html). This interface was developed so that any external process could invoke a controller response. It abstracts the request and response object to allow for multiple implementations. For example the default server engine is [Go](https://github.com/revel/revel/blob/master/server_adapter_go.go#L32) but you can also use the FastHttp [server engine](https://github.com/revel/modules/blob/master/server-engine/fasthttp/app/server-fasthttp.go) as well.

**Comment by Julio-Guerra** [comment]
For th record, I dound the answer [here](https://revel.github.io/manual/faq.html#how_do_i_integrate_existing_http.handlers_with_revel_?) and here is my code wrapping the Go HTTP server handler with our security middleware:

```
	revel.OnAppStart(func() {
		revel.AddInitEventHandler(func(event revel.Event, value interface{}) (responseOf revel.EventResponse) {
			if event == revel.ENGINE_STARTED {
				engine := revel.CurrentEngine.(*revel.GoHttpServer)
				engine.Server.Handler = sqhttp.Middleware(engine.Server.Handler)
			}
			return
		})
	})
```
