### ISSUE TITLE
Debugging support possible through LiteIDE

### ISSUE THREAD

**Issue by jetvp** [revel/revel#225]
I've seen this come up on the issues list a few times so thought I'd just pass this info on.

You can remotely debug Revel using LiteIDE (http://code.google.com/p/liteide/).  Just go to the debug menu, "Start Debugging External Application..." and then put in revel and the arguments like run project.  It will start it up and halt you at the main function from where you can move on as need be.  This can be very useful as you can imagine.

It would be cool however if each project had their own main.go which would could compile, run Revel and move on.  This would mean you end up without having to go through the steps above.

There is one issue with the above IDE, and I have put in a bug request but don't know when it will be fixed.  The projects folder list will store the temp and routes folder (under app) after the application has finished and tried deleting them meaning they are then locked by the IDE.  Thus restarting the application again will fail as it can not access the folders.  This means deleting the folders in the project tree every time or restarting the IDE, neither pleasant.  One way would be to make Revel not delete these folders for now to avoid this bug until it is fixed.

Update: The LiteIDE author just fixed the delete folder bug so it works well with it now.

**Comment by tonka3000** [comment]
Hy,

can anybody explain me how to debug an revel app in LiteIDE. Normal go app works perfect.
I can start the revel app with the debugger and it stops on the main function, but it doesn't stop on any of my own breakpoints. My revel app is a new one created with **revel new myapp**, and my breakpoint is in the Index-function of the main controller.

I start revel with "Start Debugging External Application..." with
application: revel
arguments: run myapp dev

The dev is required for the devmode otherwise gdb will crash.

Can anybody tell me what i'm doing wrong?

I use Mac OS X 10.10.1 and LiteIDE X26

Greetings
Tonka

**Comment by notzippy** [comment]
The revel command builds a go file , compiles and  a new process for running the application so it cannot be debugged in a normal manner. I created a patch in issue #294 to add support for a debug command on the command line which launches the app inside the gdb debugger https://github.com/notzippy/cmd/commit/715251e30ca70aad278c7fbffa5cb8ed5b83f08b you should be able to look at that patch to figure out what command you need to use to launch your revel app directly from the litetide. But don't forget that variable inspection is pretty much non existent in go

**Comment by tonka3000** [comment]
hey notzippy,

thanks for the information, i will try it :-)

Greetings

**Comment by brendensoares** [comment]
@notzippy @tonka3000 I'm pretty sure you can run `gdb` on the revel app via the generated `tmp/main.go`, but you can't use the `revel` command to do it, you'd have to manually build and execute the app with the correct flags that `revel` would do itself.
