### ISSUE TITLE
Catch get method set value to ptrValue

### ISSUE THREAD

**Issue by souravray** [revel/revel#479]
I'm trying to save and retrieve session user data (instance of User model struc)
I am writing following code to set the user data in Login method

``` go
    err = cache.Set(c.Session.Id(), user, 8760*time.Hour) 
```

then to retrieve the data in other method I wrote

``` go
     var user models.User
    err := cache.Get(c.Session.Id(), &user)
```

this is resulting an un-handled panic -

```
ERROR 2014/01/23 02:00:13 panic.go:23: reflect.Set: value of type *models.User is not assignable to type models.User
```

if I do 'pass by value' in the Get method like bellow 

``` go
     var user models.User
    err := cache.Get(c.Session.Id(), &user)
```

Then It returns a soft error -

```
revel/cache: attempt to get 37567655-83a6-11e3-8715-0fa2a4724295, but can not set value <models.User Value>
```

 What is the issue? Am I missing something or is it a bug?

**Comment by pedromorgan** [comment]
is the docs correct here ??
http://revel-docs.daffodil.uk.com/manual/cache.html

**Comment by brendensoares** [comment]
@pedromorgan there's a formatting issue with the `&`'s: `err := cache.Get(c.Session.Id(), &amp;products)`.

Also, we need to add `var products *[]Product` under "Session usage" (which should be uppercase "Session Usage"). Maybe we should change that from `products` to `product` to match the example above.

We could also change "Session Usage" to "Key Points" so that it's commenting on the "Cache Example".

**Comment by brendensoares** [comment]
### TODO
- [ ] emphasize need to use pointer to a pointer

**Comment by notzippy** [comment]
Closing documented
