### ISSUE TITLE
Allow local reverse proxy access to jobs module status page for IPv4/6

### ISSUE THREAD

**Issue by jgrar** [revel/revel#481]
https://github.com/robfig/revel/blob/master/modules/jobs/app/controllers/status.go#L15

Checking the header with:
revel.TRACE.Printf("%#v", c.Request.Header["X-Forwarded-For"])
TRACE 2014/01/25 05:23:10 status.go:15: []string{"::1"}

I don't know why this is being sent, maybe check this value for a local address and not existence of the header.

**Comment by brendensoares** [comment]
@drewwells there isn't any ticket for starting jobs from the jobs page. It's just a static, status listing.

@verdverm what were you thinking when you mentioned that?

1. I'm not certain of the value of restricting access to the jobs page. I agree with @pushrax that this should be up to the dever to properly configure in `app.conf`. That said, it is wise to have a safety net here in case they don't properly configure their app.
1. Alternatively, we could only allow the status page if `revel.DevMode` is true, but I see value in being able to check it in production from a trusted IP.
1. **The core issue** here is that @jgrar was unable to access the jobs status page from his local machine, because it was being proxied. **The fix** is to check proxied address like the remote address. This really has nothing to do with IPv6 it seems, though it would be nice to also check for IPv6 loopback address. I've updated this issue's title to reflect the latest understanding.

http://play.golang.org/p/xgrjhoBz7A
```go
Headers := map[string]string{"X-Forwarded-For": "::1"}
// remoteAddress is the client's remote address (e.g. 127.0.0.1, 16.1.23.240, ::1, etc), either directly or via reverse proxy (e.g. nginx)
remoteAddress := "127.0.0.1"
if proxiedAddress, isProxied := Headers["X-Forwarded-For"]; isProxied {
	remoteAddress = proxiedAddress
}
if remoteAddress != "::1" && remoteAddress != "127.0.0.1" {
	fmt.Println("Forbidden!")
	return
}
fmt.Println("Granted")
```
