### ISSUE TITLE
Improve Filter API

### ISSUE THREAD

**Issue by iamjem** [revel/revel#600]
I was looking through the way Filters are implemented (while considering helping with CSRF protection), and they seem a bit clunky and–to be honest–somewhat unsafe currently. 

As they are, they somewhat resemble the concept of Middleware found in other frameworks, with a few big differences:
- **Awkward chaining.** You have to explicitly call the next filter in the stack with with a slice of the remaining filters.
- **Filters are only called once, from top down.** Like mentioned below, no chance to operate on a `revel.Result` after its traveled through other Filters.
- **Filters get called, even if a serious error occurs in an earlier filter.** You _could_ just not call the next Filter in the slice, but as currently implemented that never seems to happen. What if a controller action gets called when there's been a serious error and it winds up modifying data in the database thinking everything is ok?
- **No good way to modify outgoing responses.** For example, the PanicFilter just uses a defer statement to blow away the existing `revel.Result`. I could see security middleware needing to check both incoming requests and outgoing responses to manipulate things like cookies and headers.

I'm proposing a more explicit API resembling how Middleware is implemented in frameworks like Django. Filter's turn into "layers" within the Middleware stack, and at any point as the request/response travels from top to bottom (request) or bottom to top (response) in the stack, any Middleware layer can modify req/resp meta data, or when necessary return a `revel.Result` then and there, preventing the other Middleware from being invoked.

I'd be happy to take a stab at starting something, assuming others think this would be a valuable update to the Filter process.

**Comment by pedromorgan** [comment]
Can I close this issue.. seems to me this lot is now in revel ;-)

**Comment by brendensoares** [comment]
@pedromorgan this is scheduled in the [Revel Roadmap](https://github.com/revel/revel/wiki/Roadmap) since we want to enhance the interface to Filters. I'm opening this back up.

**Comment by brendensoares** [comment]
@iamjem this needs an RFC in `revel/rfc`. Could you take ownership and transcribe what we've discussed here into the RFC format?

**Comment by xoen** [comment]
Hi All, newbie gopher here, so bear with me.

It would also be nice to have easy access to the request/response body from within a filter.
I wrote a couple of filters to log all the request and responses information to files and I found it more complicated than I expected (maybe also because I'm using Go for few weeks now).

I've access to a lot of nice properties/methods like `Request.Method`, `Request.RequestURI`, `Request.Referer` and `Response.Status` but when it comes to get the request body (e.g. some JSON posted by the client) or the request response (the string about to be sent to the client) it gets "interesting".

For the request I have `Request.Body` which is an `io.ReadCloser`. Once I read from it, it get empty (so if I read it in a before filter when the controller action run, its content is empty). This means I had to read it, build a new `io.ReadCloser` with the content just read and set it to the Body. It would be useful in this case to have a method which return the request body `string`.

For the response body I managed to interpolate the `revel.Response` in a string (using `"%s"`) but I didn't find any way to access the response body as string before it get sent to the client. So at the moment I just log something like `{%!s(*simplejson.Json=&{map[meta:map[page:0 totalPages:2 ...` - As you can see it's far from ideal.

I see filters as a powerful and flexible way of extend Revel to do things that you didn't think about.
Maybe it's just me and the fact that I'm new to Go, but access the request/response body as strings doesn't seem easy to me.

**Comment by anonx** [comment]
Hey, @xoen. You asked in IRC:
> Is there any way to convert a revel.Result to string? I’m talking about the revel.RenderJsonResult. It seems it has a obj property but it’s not exported

Could you please clarify what exact use-case do you have?

**Comment by xoen** [comment]
Hello @anonx, the high-level idea is to log the information about requests and responses to files for further investigation when something goes wrong.

In practice I had some troubles getting the response body before it get sent to the client.

In the controllers we call something like `c.RenderJson(resp.Json)` (the argument is a `*simplejson.Json`).
Then in the interceptor, which run after the action, I'm trying to get this JSON so I can log it (even as string would be perfectly fine).

Currently a `revel.Filter` is an interface with an `Apply` method. Is there any way to get the response body from a filter/interceptor?


PS: I know this is a ticket about improving the filter API. The reason why I commented here is because I think this is a use case someone else could have (get more information about the request/response without altering them).

**Comment by brendensoares** [comment]
@xoen you bring up some interesting ideas. Unless @iamjem has time before me, I'll be creating an RFC in the `revel/rfc` repo to solidify the changes we are discussing.

Stay tuned.

**Comment by notzippy** [comment]
Filters do have a before and after, the `FilterConfigurator` can be used to modify the filters for control on a per action basis
