### ISSUE TITLE
Websockets on Internet Explorer 11

### ISSUE THREAD

**Issue by klauspost** [revel/revel#682]
Due to an unfinished implementation of the Websocket implementation used by Revel, websockets will disconnect after 32 seconds. This of course defeats the purpose of websockets, but as far as I can tell there isn't anything that can be done from within Revel, other than perhaps switching to another websocket implementation, include a modified version or something similar.

The bug is described here:

https://code.google.com/p/go/issues/detail?id=6377

I spent some time identifying this issue, so I thought I would "document" it here in case other people run into this problem.

My "fix" was to modify my local version of go.net/websocket.

**Comment by pedromorgan** [comment]
Can we get to the bottom of the websocket implementation..

- after all the websocket is a "native go" ??
and all sort of implemets in the way..

So this page is aoutta date..
http://revel-docs.daffodil.uk.com/manual/websockets.html

and also the api..example
https://github.com/revel/samples/tree/master/chat

http://revel-docs.daffodil.uk.com/samples/chat.html

What we need in teh docs is a few examples, using various sockets.. different api and same smell.. ;-)

The websocket thing We need to write well in the manual as to how to "do it" = whichever way u want to do it.. This is the killer for revel in 2015

**Comment by brendensoares** [comment]
@pedromorgan the difference between Revel and other Go web frameworks is that we provide consistent interfaces for devers to cod apps with so that they can focus on their app logic. We don't want to make Revel so customizable that it loses its edge. Revel needs to "just work" out of the box. instead of creating an artificial layer of abstraction by allowing Revel's support for other implementations of core features, we work to support 3rd party technologies like MySQL vs MongoDB, but not Revel Sessions vs Gorilla Sessions. That may be possible, but it's not our goal.

@klauspost @pushrax Issue hasn't been updated and isn't planned for a release yet (https://github.com/golang/go/issues/6377). @pedromorgan check out golang's labels. Looks useful for Revel's GH labels.

@pushrax Gorilla's websocket package looks like a good candidate for replacing golang's incomplete implementation. I hope it doesn't have any dependencies on other Gorilla packages.

**Comment by ptman** [comment]
This seems to have been fixed upstream: https://github.com/golang/go/issues/6377

**Comment by brendensoares** [comment]
Thanks for the update @ptman!
