### ISSUE TITLE
RFCs to organize features

### ISSUE THREAD

**Issue by brendensoares** [revel/revel#827]
For example:
https://github.com/emberjs/rfcs/pull/4

This would be a better way to develop specs than using GH issues. Thoughts @revel/core ?

**Comment by pedromorgan** [comment]
We need every RFC on earth..

we want everyone one reveling in a mad idea..
eg - can I use postgis with revel..
lets go for it us nutters,.. 

its 2015.. want more and faster and more dodgy and more updates till its safe..

But yes.. RFC..
my RFC.. How can i use smarty tempating ?

**Comment by pedromorgan** [comment]
We also need to push features into develop faster.. we need to crash everyone..

**Comment by brendensoares** [comment]
@pedromorgan you're insane. I think I like you.

@anonx we should start with new complex features. We already have some pretty massive conversations here on GH, for instance #458. We MUST force our contributors, code, feedback or otherwise, to be more strict with how their thoughts are organized. RFC's would provide a structure that we MUST have if Revel is to make consistent forward movement. I don't see RFC's being used ofr existing features anytime soon, though we could consider it after we reach v1.0.

Just a note that our crazy Welsh team member, @pedromorgan has made great improvement to the Revel website (pending PR) at revel/revel.github.io#43 which should address some of your concerns with better documentation. That said, we can definitely improve understanding of the lower level code details as well. I feel our efforts to better encapsulate and modularize the code base will help us immensely in that sense. That change alone will make our code base more mentally perceivable.

I have now added the RFC repo: https://github.com/revel/rfcs

**Comment by anonx** [comment]
> @pedromorgan has made great improvement to the Revel website (pending PR) at revel/revel.github.io#43 which should address some of your concerns with better documentation.

@pedromorgan great great job. I had almost lost my faith in the fact that revel would have good docs some day. And you make me believe again :)

> That said, we can definitely improve understanding of the lower level code details as well. I feel our efforts to better encapsulate and modularize the code base will help us immensely in that sense. That change alone will make our code base more mentally perceivable.

Agree.

**Comment by pedromorgan** [comment]
Want to reopen issue to discuss one issue..

I think having a seperate Repos for RFC is not a good idea...

Simply because its not in the "revel" project itself, etc.. and imho we dont need a repo for RFC..

What I suggest as an alternative is to
- add the contributor quideline and to file RFC as issues..
- But we also ask for some preprep and some some arguments for and against..
- This would then link to direct patches etc etc..

We also want to make it simpler for newbies, who want  an out of the box experience with revel, migratign from python, pdjango, flask, or play and everyother framework..

First question I had from an php designer was .. so the tempaltes is nice, but where do I redirect all .php to no .php or html ?? for example.... ??

So Inbuild RFC's would be cool..
- but we need to stick than infor on the "website" == revel + manual etc..
- we can even make a page in jekyll for listing issues with some js.. etc

But my feeling is we nule revel/rfcs and stick em here instead..
after reading this

https://github.com/blog/1939-how-github-uses-github-to-document-github

**Comment by anonx** [comment]
@pedromorgan, advantage of a separate repo over GH issue is that every RFC would be a refined description of feature X. And no matter how many people are working on the RFC, it will be kept short so any outsider can read it.
If you are using issues you would have to read a lot of comments without any structure to understand the idea and not miss any details. If only 1 person is working on an RFC, it may work, though. And yeah, it is easier for community members to contribute to the discussion in issues. How motivated they should be to pull request something to rfcs repo?

**Comment by brendensoares** [comment]
@pedromorgan people don't follow our guidelines as it is. We really need better structure. It takes a lot of mental effort (at least for me) to fully understand and issue and then move on to understand the issue again for countless issues. The RFC framework will, as @anonx said, will allow us to more clearly communicate needs and solutions.

Also, RFCs are only intended to be temporary ways to collect software requirements aka specifications. These will be used to code an implementation that solves the correct problem. RFCs are not intended to be documentation of how Revel works. The manual, godoc and code serve that purpose.
