### ISSUE TITLE
RFC: revel devil

### ISSUE THREAD

**Issue by pedromorgan** [revel/revel#846]
The request for comment is to create and evil system so vile and throw it at your system.

     revel devil bitbucket.org/my-toilet
    > u are about to launch the revel devil, are u ready
   > enter yes no or or foo bar,, i dont care.. press z to stop
   > and then u see < stuff running >>> on shell an sim...

The devil command does a few things such as..
- launch fultimple requests for /AOL/win32.exe.favicon
- issue dos attatack at random
- throw every messed up regex test sofa
- laucnh pretend hits to your site.. laucn then as jobs..
- the @devil?hit-m-bay-one-more-time=10*1984*
- make revel crash .. 
- make your test db update and mangle data.. ie real stuff changed..

**Comment by brendensoares** [comment]
I'm not sure Revel should have these kinds of benchmarking tools built-in when there are more comprehensive tools already in existence, though this is very imaginative.

Also, it's nice that you're giving us an example of how RFCs could be used along side GH issues, but we must use our RFC repo to manage this information in order to maintain clear structure.

**Comment by pedromorgan** [comment]
Ok what I want now is revel devel .. ie a switch mode

**Comment by pedromorgan** [comment]
see Revel Devel or revel devel or revel lever

https://github.com/revel/cmd/issues/21

== lever ==
