### ISSUE TITLE
Conception of modules in Revel Framework

### ISSUE THREAD

**Issue by ghost** [revel/revel#924]
What kind of behaviour do we expect from modules?
1. Possibility of sharing:
   - Views
   - Assets (`public/` directory)
   - I18n files
   - Routes + Actions (they are useless if we have solely routes or solely actions, right?)
2. Opportunity to use module in some specific mode only (for example, `testrunner` in `dev`).

The first part (about sharing) is pretty clear. It is essential to make possible the sharing of components between apps. But as for the second one I'd like to discuss it before writing an RFC of a new architecture. Currently, modules can be added by including them in the appropriate section of `conf/app.conf`:

``` ini
# This is a sample conf/app.conf file.

[DEFAULT]
# This module will work in all modes.
module.jobs = github.com/revel/modules/jobs

[dev]
# This module will work only when in develop mode and `harness` is used.
# It will not work in `revel build`ed app even if we are running it in `dev` mode.
module.testrunner = github.com/revel/modules/testrunner

[prod]
# This module will not work due to #911.
module.auth = github.com/revel/modules/auth
```

There may be an impression that it's possible to include your module in any `section` of `INI` config. But that is a false impression. Actually, you cannot. Revel requires using `[DEFAULT]` section for modules that are planned to be included in all modes; and `[dev]` section for use in develop mode only (with `harness`). Module that is included solely in `[prod]` or in `[custom]` will not work. Not cool, but we can live with it, right? Let's move forward.

You have built an app (using `revel build ...`). It has a binary file, views, assets, and config file. You can edit the config, restart the app and changes will come into affect. Predictable behaviour, right?

**NB!** You may think that you can add some new modules to your config, or move your module to another section, or remove your module from that config. You can do it, right? Wrong, you cannot. Modules are compiled into your app during `revel build`ing. And those `module.x = ...` in config are pretty useless after building. That is anti-usable and anti-expectable. I think that is a problem that should be fixed in our new architecture.

And there are 2 options:
1. Either allow dynamic modules' loading which is hardly possible. Built apps can be run on machines without Go installed. No way to make that possible without making end-user to install some extra software.
2. Include modules in some `.go` file rather than in `app.conf` (or in some kind of build file that will not be distributed with the compiled app).

@revel/core, thoughts?

**Comment by notzippy** [comment]
@anonx I am unclear on that last bit, if I remove a module from my config it is definitely no longer in my compiled app unless it is referenced within the app somewhere else then in the app.conf (for example I use a model from a module within an app controller in my code). It is my understanding that the following occurs during a `revel build`. `revel build` generates the main.go and routes.go. These source files are created based on app.conf, routes files. Then revel executes the `go build` is to be run against the app, because of the `main.go,routes.go` files the compiler includes these modules to be compiled with your app.

**Comment by pedromorgan** [comment]
So this is an interesting read, and does clearup some things as an "end user",... 

And indeed @notzippy  raises a big issue, which is basically "compiled with config" or "compiled without" maybe ?

Can I also add, that within a "module", I expect a README.md which "would be the manual" for that module (also any other docs in md format",,

**Comment by anonx** [comment]
@notzippy To clarify that last bit. Imagine you are a maintainer of superCoolApp package in Debian. You're compiling that app and making it available to be installed using `apt-get`.

I am a user. I'm running `apt-get install superCoolApp` and trying to edit `/etc/superCoolApp/app.conf`.
1. I'm updating `http.port` to `80` and expecting it will start listening on `:80`.
2. I'm changing `results.compressed` to `true` and I want it to start compressing responses.
*Everything works as expected so far.*
3. Now I'm removing `module.static = ...` as I configured **nginx** instead. And... Nothing happens. I'm adding a new `module.smth = ...`. Nothing happens. I'm moving `module.testrunner` to `[prod]`. And still nothing happens.

As a user I have a question. Why those modules are in the configuration file if they cannot be configured? They mean nothing at that stage (after app is compiled).

**Comment by anonx** [comment]
> within a "module", I expect a README.md which "would be the manual" for that module (also any other docs in md format",, 

@pedromorgan Agree. We cannot enforce third party module makers. But for modules in `revel/modules` repo that is a must have.

**Comment by pedromorgan** [comment]
Chatted to @brendensoares about this, but its a smimple way to decouple docmentation of aany module next to source..

And that leas to the 
> revel mod create adb stuff..

I have an urging feeling to move to yaml, toml and machine readable configs...

**Comment by notzippy** [comment]
@anonx So you would like compile time directives to be separate from runtime options (isn't that easier to say ?). 

I do agree that having both (runtime and compile time directives) in a single configuration file may be confusing to the layman, and sure if you want to move the compile time directives into its own file that makes sense.

**Comment by anonx** [comment]
> So you would like compile time directives to be separate from runtime options

@notzippy Yeah, exactly.

> isn't that easier to say?

I'm not a Hemingway. More like a Plato.

**Comment by nadeemc** [comment]
Wouldn't the opposite approach also work?

Most go applications compile to a single file with embedded templates. Here you're proposing that modules are antithetical to configuration and view files and should be editable at runtime. Personally I think the opposite is more inline with Go; compile configuration and views into the app and have a smaller set of deployed files.

**Comment by anonx** [comment]
> Here you're proposing that **modules** are antithetical to configuration and view files and **should be editable at runtime**.

@nadeemc Where did I say that? My proposal is all about (as @notzippy rephrased) using separate config files for compile time directives and runtime options.

> Personally I think the opposite is more inline with Go; compile configuration and views into the app

Does that mean that in order to change port or host or DB credentials I have to install Golang, configure $GOPATH, and recompile the whole app? The same if I want to update my logo or insert Google analytics code to my `footer.html`?
There should be such an option. But that's definitely not a good default. Assets, views, and configs should be editable.

**Comment by nadeemc** [comment]
Great examples. And I see what you mean by the original suggestions now. I was (more narrowly) thinking of build systems as the use case for compiling everything.

**Comment by brendensoares** [comment]
After reading this entire thread, I think it comes down to separating compile time and runtime configs, right? If so, I agree we should do that.

I actually made a similar note about modules and how they should not be part of the runtime config.

So the question is, how do we make module inclusion configurable at compile time? I lean toward Go code instead of a `modules.conf`.

**Comment by notzippy** [comment]
@brendensoares Personally I like the configuration file. There may be other compile time directives that may not be configurable at runtime so I wouldn't label it specifically to `modules.conf`, I would call it `build.conf` or something that would point to its nature of being a compile time configuration settings. 

@anonx Me Hemingway ?!? - my wife would get a kick out of that... It was more like the third time I rewrote that comment the idea crystallized for me.

**Comment by brendensoares** [comment]
@notzippy I think I see some value in config files. I'd like to explore this more soon.

PS - I'm back >:)

**Comment by notzippy** [comment]
@brendensoares Welcome back (congrats in order?) I have not been active lately either due to hospitalization. Getting better now.

**Comment by brendensoares** [comment]
@notzippy thanks. Sorry to hear about your hospital stay. Hope you're resting up and feeling better.

Seems we've lost @anonx due to our inactivity. Last time I spoke with him we decided to simplify our goals and focus: https://github.com/revel/revel/wiki/Meetings-2015-04-16 .

As far as the topic of this thread, I feel like modules don't add much value for a developer. We don't have a module ecosystem that really takes advantage of the plugin and play potential. I'd rather focus on the priority list mentioned in the meeting notes I just mentioned.

**Comment by anonx** [comment]
@brendensoares What are your plans regarding @revel?

**Comment by notzippy** [comment]
Closing, no response
