### ISSUE TITLE
v0.12.0 bug: reverseproxy.go:184: http: proxy error: EOF

### ISSUE THREAD

**Issue by russ168** [revel/revel#927]
After upgrade to v0.12.0, when a controller do a long time processing, when RenderJson, the server will report 2015/04/22 11:24:57 reverseproxy.go:184: http: proxy error: EOF, and the brower can't receive any response.

**Comment by brendensoares** [comment]
Can you provide steps to reproduce this from a fresh `revel new testapp`?

**Comment by 1lann** [comment]
I guess the problem here would be that there is a HTTP 500 Server Error with an empty body response returned if the controller takes too long to respond (ie. it timeouts). Perhaps a HTTP 504 Gateway Timeout should be produced instead, and possibly make it so reverse proxy errors do render error pages.

Example controller code:
```go
package controllers

import "github.com/revel/revel"
import "time"

type App struct {
	*revel.Controller
}

func (c App) Index() revel.Result {
	time.Sleep(3 * time.Minute)
	return c.Render()
}
```

You may want to leave the page loading in the background, as it does take a long time to timeout.

**Comment by russ168** [comment]
Before v0.12.0, even execute a long time task(took more than 10 minutes), it won't occur any problem. The browser can get the results finally.

**Comment by chqsark** [comment]
I'm having the same problem. In my case, I called a function which takes about 1min before redirecting it to the next page. Everything works fine until the redirection happens and it gives the http proxy EOF error. In the old version revel, everything was fine.

**Comment by anonx** [comment]
Can confirm. Due to default 1 Minute timeouts that were introduced in v0.12 (#843) request cannot be finished if it takes too much time.

@russ168, @chqsark If you need actions that are processing something for so long, customize timeouts by editing your `init.go` or some controller:
```go
func init() {
	revel.OnAppStart(func() {
		// 0 means there will be no any timeout at all.
		revel.Server.ReadTimeout = 0
		revel.Server.WriteTimeout = 0
	})
}
```

Thank you @1lann for your help. I agree, 504 error should be shown instead of 500. Moreover, not related to the issue but 500 errors should contain responses (that is another change that was introduced by #881, we discussed the solution with @brendensoares in IRC).

@chqsark How did you measure the speed?

**Comment by chqsark** [comment]
@anonx, thanks a lot! it works well after I set the timeout to 0. 

The speed issue is found to be a mysql insertion loop. It may have nothing to do with revel. However, I'm still figuring out why the speed is so fast on my mac but so slow on ubuntu. I am using prepare statement and database/sql package in golang, and Mysql is local.

**Comment by michaelbironneau** [comment]
I got the same problem in a stress test - a small proportion of requests produced this error when an upstream database was under stress, same fix as above worked to resolve the issue.

**Comment by brendensoares** [comment]
[Defaults have been added and can be overridden](https://github.com/revel/revel/blob/master/skeleton/conf/app.conf.template#L72) now. This issue should now be resolved.
