### ISSUE TITLE
Controllers in sub directory of controllers

### ISSUE THREAD

**Issue by amlwwalker** [revel/revel#989]
If I want to organise my controllers a bit, by putting some of them in a sub directory, what is the process? Just moving it doesn't work out of the box, I feel there is some routes config I need. For instance this is my `app/controllers` directory structure:

```
├── Modules
│   └── Sample.go
├── app.go
```
I can access any endpoint in the app file by going to (for instance) `127.0.0.1:9000/App/endpoint`, but if I do the same for an end point in `Modules/Samples.go`, for instance `Sample()` I get `revel/controller: failed to find action Sample`. I tried also
`127.0.0.1:9000/App/Modules/sample` however that gives the same error.

**Comment by alkchr** [comment]
@amlwwalker  You can create any number of subdirectories as long as your modules are `controllers` packages.

So, your structure should look like:
> ├── Modules
> │   └── Sample.go `package controllers`
> ├── app.go `package controllers`

You can access your `Modules/Sample.go` as if it were a regular `Sample.go` at the root of `app/controllers/` directory: `127.0.0.1:9000/ModuleControllerName/ActionName`.

**Comment by amlwwalker** [comment]
Hmm strange...

My folder structure is like this

![image](https://cloud.githubusercontent.com/assets/2920180/10117544/9c8a2886-6452-11e5-8e0f-81c5a7d92304.png)

If I want to access an action in app.go, such as `func (c App) Documents() revel.Result {` I go to `127.0.0.1:9000/App/Documents` and that works.

If I want to access the action `func (c App) Sample() revel.Result {` in sample.go, I think I should go to `127.0.0.1:9000/App/Sample` but I get

![image](https://cloud.githubusercontent.com/assets/2920180/10117555/3f0353bc-6453-11e5-96ad-d45595043067.png)

Both are in `package controllers`

**Comment by alkchr** [comment]
All controllers must have unique names. If you're using `App` for your controller inside `app.go` you cannot use it for one in `modules/sample.go`.

**Comment by amlwwalker** [comment]
Right, ok... so that makes me wonder why it wouldn't be `127.0.0.1:9000/App/Module/Sample` if its a seperate controller, but is in a subdirectory below the `App` controller.

The top of my `Sample.go` looks like this now:

```
package controllers
type Module struct {
    *revel.Controller
}
func (c Module) Sample() revel.Result {
```

When I go to `http://127.0.0.1:9000/Module/Sample` I get

![image](https://cloud.githubusercontent.com/assets/2920180/10117728/76bbf85e-6458-11e5-9aaf-271201054969.png)

Do I need to initialise an instance of `Module` somewhere? I presume the instance of `App` is initialised somewhere but I can't find it

**Comment by alkchr** [comment]
You don't need to initialize anything, just restart `revel`.

**Comment by amlwwalker** [comment]
Sweet! All is working. I thought it would recompile, but a restart did it

**Comment by pedromorgan** [comment]
Hang on a minit.. does this mean we can have sub dirs of controllers ???

**Comment by brendensoares** [comment]
@pedromorgan yes, the controllers folder is recursively loaded:
1. [Check Code Paths](https://github.com/revel/revel/blob/8d01a054f6bca9430b3e497fe7b4f20ec8f054ce/revel.go#L359)
2. [Harness Build Command](https://github.com/revel/cmd/blob/62fc677f3a4043183ad83ccb9cc32165e91dc72e/harness/build.go#L30)
3. [Loads all Go files](https://github.com/revel/cmd/blob/master/harness/reflect.go#L119)

From there, it's based on Go packages, not folders (which is why the controller names need to be unique). The folders are only there for organizational purposes. I'm 99% sure all the above is accurate :)

There has been other conversations about using modules to further organize app code, which should allow for name spacing of controllers essentially, but that's a different conversation for another time.

**Comment by brendensoares** [comment]
Closing as there seem to be no action items here. Thanks all.
